"""Initial migration

Revision ID: 9885f726df15
Revises: 
Create Date: 2024-07-29 14:26:49.921342

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9885f726df15'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cow',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('birthdate', sa.Date(), nullable=True),
    sa.Column('dam_id', sa.Integer(), nullable=True),
    sa.Column('sire_id', sa.Integer(), nullable=True),
    sa.Column('sex', sa.String(length=1), nullable=True),
    sa.Column('registration', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['dam_id'], ['cow.id'], ),
    sa.ForeignKeyConstraint(['sire_id'], ['cow.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('feeding',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cow_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('feed_type', sa.String(length=50), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['cow_id'], ['cow.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('medication',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cow_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('drug_name', sa.String(length=100), nullable=True),
    sa.Column('dosage', sa.Float(), nullable=True),
    sa.Column('cost', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['cow_id'], ['cow.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('note',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cow_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['cow_id'], ['cow.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reproduction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cow_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('event_type', sa.String(length=20), nullable=True),
    sa.Column('semen_name', sa.String(length=100), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['cow_id'], ['cow.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('show',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cow_id', sa.Integer(), nullable=True),
    sa.Column('show_date', sa.Date(), nullable=True),
    sa.Column('show_name', sa.String(length=100), nullable=True),
    sa.Column('place', sa.Integer(), nullable=True),
    sa.Column('fees', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['cow_id'], ['cow.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('weight',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cow_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['cow_id'], ['cow.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('weight')
    op.drop_table('show')
    op.drop_table('reproduction')
    op.drop_table('note')
    op.drop_table('medication')
    op.drop_table('feeding')
    op.drop_table('cow')
    # ### end Alembic commands ###
