"""Add password column to User

Revision ID: bfd5e9640b14
Revises: 
Create Date: 2024-01-16 23:47:07.306562

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bfd5e9640b14'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reproduction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('semen_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('due_date', sa.Date(), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.String(length=20), nullable=True))
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=64),
               existing_nullable=True)
        batch_op.create_unique_constraint(None, ['username'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('username',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.drop_column('password')

    with op.batch_alter_table('reproduction', schema=None) as batch_op:
        batch_op.drop_column('due_date')
        batch_op.drop_column('semen_name')

    # ### end Alembic commands ###
